### ISSUE TITLE
weak augmentation

### ISSUE THREAD

**Issue by minju-Kang** [hust-jy/DDS3D#1]
Hi, thank you for sharing your code!

I want to know what augmentation you used for weak augmentation, and where it is implemented.
In the paper, you said that augmentation strategies are same with 3DIoUMatch,
but I can't find the weak augmentation in yours and also 3DIoUMatch code.

Thank you for reading my question!

**Comment by SII-Whaleice** [comment]
Thank you for your attention.
I actually didn't do any data augmentation on the unlabeled data that was fed into the teacher network. I conducted experiments and found that using any single data augmentation was not as good as using the original data. The weak enhancement described here follows 3DIoUMatch.

**Comment by minju-Kang** [comment]
I got it!
Thank you so much!
